### ISSUE TITLE
Add bf:Contribution at the instance level

### ISSUE THREAD

**Issue by NancyL** [LD4P/ld4ptemplates#38]
ld4p:RT:bf2:Monograph:Instance

**Describe requested enhancement**
Add bf:Contribution at the Instance level RT. The cohort and affinity group have expressed a need for this, though I think we need to collect use cases to make sure

**Comment by NancyL** [comment]
Do any of you see use cases for instance, particularly? Are there use cases for adding a contribution to the item template. This would be for the general monograph templates, not specialty ones.

**Comment by NancyJean** [comment]
I like the idea of a Contributor at the Item level for copies that are glossed (e.g., Tom Jefferson put marginalia in his copy of The Wealth of Nations) or signed or have bookplates from a personal library, et al.  It brings that Item level data into the appropriate level of description and could open up discovery to a slew of Item resources that might otherwise remain hidden.

I'm not sure about Instances, however, because I don't know where the line is drawn between creating an Instance and a new Work.  If you have a difference in contribution, e.g., a new preface by someone who's not the author, is that a new Work?  I agree that we need to know the use cases for a new Contributor in Instance that would not require creating a new Work and I don't have any.

**Comment by timathom** [comment]
I agree with @NancyJean regarding bf:Contribution at the Item level, and I think the use cases there are readily apparent. At the Instance level, I think most, if not all, contribution use cases are covered by provision activities (Publication, Distribution, Manufacture, Production). Publication and Distribution are straightforward. However, Manufacture (printer, typographer, etc.) and Production can represent different kinds of contributions and roles. As such, there is a use case for embedding bf:Contribution resources within Manufacture and Production activities. This is what we have done in our [Monograph Instance template](https://sinopia.io/editor/Yale:RT:BF2:Monograph:Instance:CtY). (By the way, is there a reason that the general LD4P Monograph Instance template doesn't include a Production template?)

**Comment by NancyL** [comment]
Do not include this in instance template, since covered by provision activities. Consider adding roles for bf:Manufacture.

**Comment by NancyL** [comment]
Tim, regarding bf:Production. I left it out because in RDA it is only for unpublished materials and I thought of this template as only for published ones. Should we change that? Or are you using it in a different way than RDA? The bf definition is certainly ambiguous
